### ISSUE TITLE
Add license for re-use by other projects

### ISSUE THREAD

**Issue by jpconstantineau** [freemansoft/Adafruit-Trinkey-CircuitPython#1]
Hi,

Can you add a license to enable re-use in other projects?
I am specifically looking at the  Indicator-Light-Neopixel code as it allows getting a visible indication of status from code running on a server/raspberry pi.

I am recommending MIT as both the neopixel and logging libraries are using these but it's your call...

**Comment by freemansoft** [comment]
Done!

**Comment by jpconstantineau** [comment]
Thanks. 

I see the other 2 files but not this one:
https://raw.githubusercontent.com/freemansoft/Adafruit-Trinkey-CircuitPython/main/Indicator-Light-neopixel/main.py

**Comment by freemansoft** [comment]
Fixed. This is why committers shouldn't be allowed to close their own work items

**Comment by jpconstantineau** [comment]
Thanks. I know exactly how that feels...

I use the neokey as a mouse jiggler.  Instead of random movements, I used Lorenz' attractor chaos equations to make the mouse move chaotically.   I'll have to create a repo for and post it. I am sure people would be interested...

**Comment by jpconstantineau** [comment]
The 3 python files have license and copyright details in their headers. This should be good. 

Any thoughts on a "License" file in the root folder?  GitHub picks it up and shows the license details on the right hand side of the repo main page.

**Comment by freemansoft** [comment]
I'm thinking of adding a return message for any command.  Something like `OK`  or `ERROR`.

Then a program could send `\n` until it gets `OK`

**Comment by freemansoft** [comment]
Done
